# Generated by Django 4.2 on 2023-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_products_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
