# Generated by Django 4.2 on 2023-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_products_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
