# Generated by Django 4.2 on 2023-04-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='file',
        ),
    ]
