# Generated by Django 4.2 on 2023-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_products_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
