# Generated by Django 4.2 on 2023-05-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
