# Generated by Django 4.2 on 2023-05-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_comment_created_at_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('Soo bad', 1), ('Badly', 2), ('Not bad', 3), ('Well', 4), ('Soo well', 5)], max_length=255),
        ),
    ]
