# Generated by Django 4.2 on 2023-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_basket_alter_comment_options_basketitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
