# Generated by Django 4.2 on 2023-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_basketitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
