# Generated by Django 4.2 on 2023-05-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_basketitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('Online Payment', 'Online Payment'), ('Cash on Delivery', 'Cash on Delivery'), ('POS on Delivery', 'POS on Delivery')], max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.basket')),
            ],
        ),
    ]
